### ISSUE TITLE
TAG300N1000 serial launch imu data is wrong

### ISSUE THREAD

**Issue by TZECHIN6** [MapIV/tamagawa_imu_driver#11]
### Setup configuration
IMU model: TAG300N1000
OS: Ubuntu 22.04
ROS: ROS2 humble

### Reproduce
1. git clone this package and switch to Humble branch
2. ros2 launch tamagawa_imu_driver serial_AU7554N.launch

```
---
header:
  stamp:
    sec: 1705563680
    nanosec: 445984098
  frame_id: imu
orientation:
  x: 0.0
  y: 0.0
  z: 0.0
  w: 1.0
orientation_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
angular_velocity:
  x: 0.0008522115488253562
  y: 0.0003195793308095086
  z: -0.023542344036300466
angular_velocity_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
linear_acceleration:
  x: -0.35400390625
  y: -9.686279296875
  z: 1.0894775390625
linear_acceleration_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
---
```

The sensor is placed flat on a desk, Z is pointing downward. However, the serial driver is wrongly decode the message (please see above imu/data log.

*Remark: CAN driver can correctly decode the IMU package as expected*

**Update**
https://github.com/tier4/tamagawa_imu_driver/tree/feature/TAG300
Actually, there is a fork from Tier 4 as well, but the last update date is older than this repository, can anyone suggest which one should I go for?
